interface ITranslates {
  [key: string]: string;
}
export const translates = Object.freeze<ITranslates>({
  'Courses': 'Khoá học',
  'Career path': 'Tuyển dụng',
  'Hire talent': 'Góc nghề nghiệp',
  'Find a mentor': 'Tìm kiếm mentor',
  'Become a mentor': 'Trở thành Mentor',
  'Supercharge your career': 'Supercharge your career',
  'Meet 500+ mentors from top companies': 'Gặp gỡ 500+ Mentors đến từ hơn 30+ công ty hàng đầu',
  'Find a mentor in your field': 'Tìm kiếm Mentor trong lĩnh vực mà bạn đang theo đuổi',
  'Technology': 'Công nghệ',
  'Product': 'Sản phẩm',
  'Business Analytics': 'Business Analyst',
  'Data': 'Data',
  'Marketing': 'Marketing',
  'Freelancing': 'Freelancing',
  'Human Resources': 'HR',
  'Content Creation': 'Sáng tạo nội dung',
  'Startups': 'Startups',
  'Scholarships': 'Học bổng',
  'Business Development': 'Du học',
  'HR': 'Bán hàng',
  'Others': 'Khác',
  'Discover your personalized learning courses': 'Khám phá những khoá học thiết kế riêng cho bạn',
  'Tailor courses to your unique needs with the most robust customisation tools in the market': 'Tuỳ theo những kỹ năng bạn còn yếu hoặc muốn phát triển thêm qua lời khuyên của mentor, thông tin từ Kho nghề nghiệp',
  'Design': 'Thiết kế',
  'Popular': 'Phổ biến nhất',
  'Development': 'Công nghệ',
  'Leap 10x career growth with world-class mentors': 'Bước nhảy vọt sự nghiệp với những người cố vấn 1:1',
  'If you’re looking for advice, jamming, or networking, Guidemee lets you freely schedule a 1:1 mentorship session in fun new ways and work with them directly.': 'Nếu bạn đang tìm kiếm lời khuyên, sự kết nối - Guidemee cho phép bạn tự do lên lịch phiên cố vấn 1:1 theo những cách mới thú vị và  trực tiếp với họ.',
  'Visit a career center': 'Khám phá Trung tâm nghề nghiệp',
  'Boost your credentials to get hired fast': 'Nâng cao uy tín hồ sơ và thành tích để tìm một công việc nhanh chóng',
  'Out of a job, not out of touch. Guidemee lets you list yourself as a talent in the community and get vouched by mentors - boosting your credentials to get hired fast.': 'Guidemee cho phép bạn liệt kê mình là một tài năng trong cộng đồng và được các Mentor xác nhận - nâng cao thông tin tìm việc của bạn để được tuyển dụng nhanh chóng.',
  'Taking the time to assess both yourself and your career needs will help you discover the right career path. More than 10,000 job position, more than 300 job categories with various career development orientation from industry experts.': 'Dành thời gian để đánh giá cả bản thân và nhu cầu nghề nghiệp của bạn sẽ giúp bạn khám phá ra con đường sự nghiệp đúng đắn. Hơn 10,000 vị trí nghề nghiệp, hơn 300 nghành nghề khác nhau với các hướng phát triển đa dạng theo tiêu chuẩn và nghiên cứu từ những chuyên gia hàng đầu',
  '97% of mentees say having a mentor makes a positive impact to their future career progression.': '97% cá nhân có những chuyển biến tích sự trong sự nghiệp của họ nhờ sự giúp đỡ của Mentor',
  'Meet our mentors': 'Khám phá những Mentor nổi bật',
  'What our members are saying': 'Mentee nói gì về chúng tôi',
  'Guidemee is a mentorship and expert platform that helps you accelerate your career in various fields.': 'Guidemee là nền tảng kết nối Mentor - Mentee trên nhiều lĩnh vực hướng tới những cơ hội việc làm hàng đầu cho giới trẻ Việt Nam',
  'Mentee': 'Mentee',
  'Mentor': 'Mentor',
  'Company': 'Công ty',
  'Legal': 'Legal',
  'About us': 'Về chúng tôi',
  'Terms of service': 'Điều khoản sử dụng',
  'Help center': 'Trung tâm trợ giúp',
  'Privacy policy': 'Privacy policy',
  'Partnerships': 'Hợp tác',
  'FAQ': 'FAQ',
})
